config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
      resources :icons
      resources :users

      root to: "icons#index"
    end
  resources :icons do
    member do
      get :like
    end
  end
  resource :user, only: [:show] #test de création de route pour afficher le status de l'utilisateur
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "icons#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/icon.rb
class Icon < ApplicationRecord
    has_and_belongs_to_many :users

    def liked_by?(user)
        return false if user.nil?
        user.in?(users)
    end

    def toggle_like_for(user)
        if user.nil?
            return false
        else
            liked_by?(user) ? users.delete(user)
                            : users << user 
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :icons 
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
      before_action :authenticate_user!
      before_action :authenticate_admin

    def authenticate_admin
      redirect_to '/', alert: 'Not authorized.' unless current_user && access_whitelist
      # TODO Add authentication logic here.
    end
    private
      def access_whitelist
        current_user.try(:admin?) || current_user.try(:door_super?)
      end
    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/icons_controller.rb
module Admin
  class IconsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  before_action :set_icon, only: %i[ show edit update destroy ]
  
  before_action :authenticate_user!, only: :like

  # GET /icons or /icons.json
  def index
    @term = params[:term]
    @icons = @term.blank? ? Icon.all 
                          : Icon.where("title LIKE (?)", "%#{@term}%")
  end

  # GET /icons/1 or /icons/1.json
  def show
  end

  # GET /icons/new
  def new
    @icon = Icon.new
  end

  # GET /icons/1/edit
  def edit
  end

  # POST /icons or /icons.json
  def create
    @icon = Icon.new(icon_params)

    respond_to do |format|
      if @icon.save
        format.html { redirect_to icon_url(@icon), notice: "Icon was successfully created." }
        format.json { render :show, status: :created, location: @icon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /icons/1 or /icons/1.json
  def update
    respond_to do |format|
      if @icon.update(icon_params)
        format.html { redirect_to icon_url(@icon), notice: "Icon was successfully updated." }
        format.json { render :show, status: :ok, location: @icon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icons/1 or /icons/1.json
  def destroy
    @icon.destroy!

    respond_to do |format|
      format.html { redirect_to icons_url, notice: "Icon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like 
    icon_id = params[:id]
    icon = Icon.find icon_id
    icon.toggle_like_for(current_user)
    redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icon
      @icon = Icon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def icon_params
      params.require(:icon).permit(:title, :image, :kind, :tags)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user! # Ensures user is authenticated before accessing this controller
  
    def show
      @user = current_user
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/views/icons/_form.html.erb
<%= simple_form_for icon do |form| %>
  <% if icon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(icon.errors.count, "error") %> prohibited this icon from being saved:</h2>

      <ul>
        <% icon.errors.full_messages.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.input :title %>
  <%= form.input :image %>
  <%= form.input :kind %>
  <%= form.input :tags %>
  
  <%= form.submit %>
<% end %>

app/views/icons/_icon.html.erb
<div id="<%= dom_id(icon) %>" class="card col-3">
  <img class="card-img-top" src="<%= icon.image %>">
  <div class="card-body">
    <h3 class="card-title"><%= icon.title %></h3>
    <p>
      <strong>Type:</strong>
      <%= icon.kind %>
    </p>
    <p>
      <strong>Tags:</strong>
      <%= icon.tags %>
    </p>
    <a href="<%= icon.image %>" download="test" class="btn btn-link">
      <%= image_tag("download.svg", alt: "Télécharger cette image") %>
    </a>
    <%= link_to like_icon_path(icon.id), class: "text-dark text-decoration-none" do %>
      <% if icon.liked_by?(current_user) %>
        <%= image_tag("fav_plein.svg", alt: "J'aime déjà") %>
      <% else %>
        <%= image_tag("fav_vide.svg", alt: "Je n'aime pas") %>
      <% end %>
      <%= icon.users.count %>
    <% end %>
  </div>
</div>

app/views/icons/edit.html.erb
<h1>Modifier cet icône</h1>

<%= render "form", icon: @icon %>

<br>

<div>
  <%= link_to "Show this icon", @icon %> |
  <%= link_to "Back to icons", icons_path %>
</div>

app/views/icons/index.html.erb
<div class="row">
  <div class="jumbotron col-12">
    <h1 class="display-4">AI Icons</h1> 
    <p class="lead">Ce site est une librairie gratuite d'icônes en 3D générées par Midjourney.</p>
      <% if user_signed_in? %> 
      <div> Bonjour <%= current_user.email %>, nous sommes heureux de te voir</div> 
      <% end %>
  </div>
</div>

  <%# Barre de recherche %>
  <div class="row">
    <div class="col-md-6 col-lg-4">
      <form target="" method="">
        <div class="input-group mb-3">
          <input name="term" value="<%= @term %>" type="text" class="form-control" placeholder="Rechercher" aria-label="Rechercher" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">Rechercher</button>
          </div>
        </div>
      </form>
    </div>
  </div>

<div id="icons" class="row gap-3">
  <% @icons.each do |icon| %>
    <%= render icon %>
  <% end %>
</div>

app/views/icons/new.html.erb
<h1>Nouvelle icône</h1>

<%= render "form", icon: @icon %>

<br>

<div>
  <%= link_to "Retourner au menu", icons_path %>
</div>

app/views/icons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @icon %>

<div>
  <%= link_to "Modifier cet icône", edit_icon_path(@icon) %> |
  <%= link_to "Retourner au menu", icons_path %>

  <%= button_to "Détruire cet icône", @icon, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IconsAi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  
  <%# nav bar %>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid container">
        <a href="/" class="navbar-brand">Ai Icons</a> 
        <div class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if user_signed_in? %> 
        <%= button_to  "Se déconnecter", destroy_user_session_path, method: :delete, class:"btn btn-outline-success me-2 my-2 my-lg-0 end" %> 
        <% if current_user.try(:admin?) %>
        <a href="/admin/" class="btn btn-outline-secondary nav-item me-2 my-2 my-lg-0 end">Panel admin</a>
        <% end %>
        <% unless current_page?(user_path) %>
        <%= link_to "Mes likes", user_path, class:"btn btn-outline-danger nav-item me-2 my-2 my-lg-0 end" %>
        <% end %>
      <% else %>
        <%= button_to "Se connecter", new_user_session_path, class:"btn btn-outline-success nav-item me-2 my-2 my-lg-0 end" %> 
      <% end %>
    </div>
  </div>
</nav>

  <div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/show.html.erb
<h1>Mes likes</h1>
<p><strong>Email:</strong> <%= @user.email %></p>

<div id="icons" class="row gap-3">
  <% @user.icons.each do |icon| %>
    <%= render icon %>
  <% end %>
</div>